# Settings and .env keys
ENV_SECRET_KEY = 'SECRET_KEY'
ENV_DEBUG = 'DEBUG'
ENV_DEVELOPMENT_MODE = 'DEVELOPMENT_MODE'
ENV_ALLOWED_HOSTS = 'ALLOWED_HOSTS'

# Api helper keys
NAME = 'name'
MESSAGE = 'message'
